name: docker4640

on:
  push:
    branches:
      - "main"
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push analitic image
        uses: docker/build-push-action@v3
        with:
          context: analitics
          push: true
          tags: alexhzzz/analitic_app:latest
          
      - name: Build and push output app image
        uses: docker/build-push-action@v3
        with:
          context: app_code
          push: true
          tags: alexhzzz/output_app:latest
          
      - name: Build and push input app image
        uses: docker/build-push-action@v3
        with:
          context: input/nodeinput
          push: true
          tags: alexhzzz/input_app:latest
          
      - name: Build and push input login image
        uses: docker/build-push-action@v3
        with:
          context: login/nodelogin
          push: true
          tags: alexhzzz/input_login:latest
          tags: alexhzzz/input_app:latest
          
      - name: Build and push result login image
        uses: docker/build-push-action@v3
        with:
          context: result_login/nodelogin
          push: true
          tags: alexhzzz/result_login:latest
